TERMINAL_STATUS = (
    ('ACTIVE', 'ACTIVE'),
    ('INACTIVE', 'INACTIVE'),
    ('ARCHIVE', 'ARCHIVE'),
    ('DEACTIVATED', 'DEACTIVATED'),
    ('ASSIGNED', 'ASSIGNED'),
    ('UNASSIGNED', 'UNASSIGNED'),
    ('FAULTY', 'FAULTY'),
    ('DEPRECATED', 'DEPRECATED'))

TERMINAL_LOG_TYPE = (
    ('ASSIGNED', 'ASSIGNED'),
    ('UNASSIGNED', 'UNASSIGNED'),
    ('REASSIGNED', 'REASSIGNED'),
    ######## Terminal Update Status ##########
    ("FAULTY", "FAULTY"),
    ("FIXED", "FIXED"),
    ('DEPRECATED', 'DEPRECATED'),
    ('ARCHIVE', 'ARCHIVE'),
    ('UNARCHIVE', 'UNARCHIVE'),
)
