version: '3.8'

services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    volumes:
      - ./app:/app
      - ./docker/local/entrypoint.sh:/app/entrypoint.sh
      - simone-local-static-data:/vol/web
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    networks:
      - simone

  db:
    image: postgres:14.5-alpine3.16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - simone-local-db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - simone

  redis:
    image: redis:alpine
    networks:
      - simone

  celery:
    <<: *api
    command: >
      sh -c "celery -A core worker -l INFO"
    ports: []
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - api
    networks:
      - simone

  celery-beat:
    <<: *api
    command: celery -A core beat -l info
    ports: []
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery
    networks:
      - simone


volumes:
  simone-local-static-data:
  simone-local-db:

networks:
    simone:
      driver: bridge
