USER_ROLE = (
    ('SUPER_ADMIN', 'SUPER_ADMIN'),
    ('HYBRID_ADMIN', 'HYBRID_ADMIN'),
    ('TMS_ADMIN', 'TMS_ADMIN'),
    ('AMS_ADMIN', 'AMS_ADMIN'),
    ('HYBRID_USER', 'HYBRID_USER'),
    ('TMS_USER', 'TMS_USER'),
    ('AMS_USER', 'AMS_USER')
)

STATUS_OPTIONS = (
    ('PENDING', 'PENDING'),
    ('ACTIVE', 'ACTIVE'),
    ('ARCHIVE', 'ARCHIVE')
)

GENDER_OPTION = (
    ('MALE', 'MALE'),
    ('FEMALE', 'FEMALE')
)

TOKEN_TYPE = (
    ('ACCOUNT_VERIFICATION', 'ACCOUNT_VERIFICATION'),
    ('PASSWORD_RESET', 'PASSWORD_RESET'),
)