# Generated by Django 4.0 on 2022-12-12 14:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('no_of_terminals', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('serial_no', models.CharField(max_length=200)),
                ('IMEI', models.CharField(max_length=200)),
                ('model_no', models.CharField(max_length=200)),
                ('os_version', models.CharField(max_length=200)),
                ('app_version', models.CharField(max_length=200)),
                ('device_tag_no', models.CharField(max_length=200, null=True)),
                ('merchant_ref', models.UUIDField(blank=True, null=True)),
                ('terminal_battery', models.CharField(blank=True, max_length=200, null=True)),
                ('terminal_charger', models.CharField(blank=True, max_length=200, null=True)),
                ('terminal_manual', models.CharField(blank=True, max_length=200, null=True)),
                ('terminal_pin', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('ARCHIVE', 'ARCHIVE'), ('DEACTIVATED', 'DEACTIVATED'), ('ASSIGNED', 'ASSIGNED'), ('UNASSIGNED', 'UNASSIGNED'), ('FAULTY', 'FAULTY'), ('DEPRECATED', 'DEPRECATED')], default='UNASSIGNED', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TerminalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_ref', models.UUIDField(blank=True, null=True)),
                ('type', models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('UNASSIGNED', 'UNASSIGNED'), ('REASSIGNED', 'REASSIGNED'), ('FAULTY', 'FAULTY'), ('FIXED', 'FIXED'), ('DEPRECATED', 'DEPRECATED'), ('ARCHIVE', 'ARCHIVE'), ('UNARCHIVE', 'UNARCHIVE')], max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='terminal_log_documents/')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TerminalShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_code_name', models.CharField(max_length=100)),
                ('device_shipped', models.CharField(help_text='e.g. D20 android terminals', max_length=100)),
                ('oem', models.CharField(help_text='e.g. D20 group', max_length=100)),
                ('shipment_id', models.CharField(editable=False, max_length=100)),
                ('shipment_partner', models.CharField(max_length=100)),
                ('date_acquired', models.DateField()),
                ('date_shipped', models.DateField()),
                ('date_received', models.DateField()),
                ('qty_paid_for', models.PositiveIntegerField()),
                ('shipment_value', models.PositiveIntegerField()),
                ('qty_shipped', models.PositiveIntegerField()),
                ('qty_received', models.PositiveIntegerField()),
                ('components', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='TerminalStatusUpdateFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='terminal_log_documents/')),
                ('terminal_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_update_files', to='tms.terminallog')),
            ],
        ),
        migrations.CreateModel(
            name='TerminalShipmentFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='shipment_documents/')),
                ('terminal_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tms.terminalshipment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
