# Generated by Django 4.0 on 2022-12-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tms', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminallog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminallog_actor', to='user.user'),
        ),
        migrations.AddField(
            model_name='terminallog',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_log', to='tms.terminal'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_group', to='tms.group'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='shipment_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_batch', to='tms.terminalshipment'),
        ),
    ]
